# Generated by Django 3.2.20 on 2023-09-05 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_auto_20230905_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='saved_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='paper_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='saved_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
