services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env_backend
  backend:
    build: ./backend
    command: >
      bash -c "python backend/manage.py migrate --fake sessions zero
      && python backend/manage.py migrate --fake-initial
      && python backend/manage.py collectstatic --no-input
      && python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./backend/static:/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env_backend
    depends_on:
      - db
    links:
      - db
  frontend:
    build: ./frontend
    env_file:
      - ./.env_frontend
    volumes:
      - .:/code
      - ./frontend/build:/build
    ports:
      - "3000:3000"
    depends_on:
      - backend