version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./backend
    command: >
      bash -c "dockerd >/dev/null 2>&1 & sleep 10
      && python backend/manage.py migrate --fake sessions zero
      && python backend/manage.py migrate --fake-initial
      && python backend/manage.py collectstatic --no-input
      && python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./backend/static:/static
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    links:
      - db
  nginx:
    build: ./nginx
    volumes:
      - ./backend/static:/static
    ports:
      - "80:80"
    depends_on:
      - backend
  frontend:
    build: ./frontend
    volumes:
      - .:/code
      - ./frontend/build:/build
    ports:
      - "3000:3000"
    depends_on:
      - backend
  ollama:
    build: ./ollama
    # set environment variables
    environment:
      - OLLAMA_ORIGINS=http://localhost:*
    volumes:
        - ./ollama/models:/root/.ollama/models
    ports:
        - 11434:11434
    container_name: ollama
    deploy:
      resources:
        limits:
          cpus: '10.0'
          memory: 8G