# Generated by Django 3.2.19 on 2023-05-04 16:13

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(default='-')),
                ('question_type', models.CharField(choices=[('general', 'general'), ('biomedical', 'biomedical'), ('-', '-')], default='-', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatGPT', models.IntegerField(null=True)),
                ('AI21', models.IntegerField(null=True)),
                ('OpenAssistant', models.IntegerField(null=True)),
                ('BioGPT', models.IntegerField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(default='-')),
                ('model_type', models.CharField(choices=[('chatGPT', 'chatGPT'), ('AI21', 'AI21'), ('OpenAssistant', 'OpenAssistant'), ('BioGPT', 'BioGPT'), ('-', '-')], default='-', max_length=40)),
                ('rating', models.IntegerField(choices=[(1, 'positive'), (0, 'neutral'), (-1, 'negative')], default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.question')),
            ],
        ),
    ]
