# Generated by Django 3.2.20 on 2023-09-05 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_auto_20230814_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='-', max_length=200)),
                ('zotero_id', models.CharField(default='-', max_length=40)),
                ('dataset_size', models.IntegerField(default=0)),
                ('dataset_date_time', models.DateTimeField(default='2023-01-01 00:00:00')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='source_page',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='source_paper',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_comment',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='model_type',
            field=models.CharField(choices=[('chatGPT', 'chatGPT'), ('AI21', 'AI21'), ('BioGPT', 'BioGPT'), ('BioGPT-ft', 'BioGPT-ft'), ('Llama2', 'Llama2'), ('Llama2-ft', 'Llama2-ft'), ('-', '-')], default='-', max_length=40),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_paper', models.TextField(default='-')),
                ('source_page', models.IntegerField(default=0)),
                ('context', models.TextField(default='-')),
                ('distance', models.FloatField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.TextField(default='-')),
                ('paper_attachment', models.FileField(default='-', upload_to='papers/')),
                ('paper_date_time', models.DateTimeField(default='2023-01-01 00:00:00')),
                ('paper_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_dataset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testdb.dataset'),
            preserve_default=False,
        ),
    ]
