upstream django {
	server backend:8000;
}

upstream frontend {
	server frontend:3000;
}

# upstream label_studio {
# 	server label_studio:8080;
# }

server {
	listen 80;
	# server_name YOUR_IP_ADDRESS;
	# server_name  10.300.60.200; - for example
	keepalive_timeout 10000;
	proxy_read_timeout 10000;
	proxy_connect_timeout 10000;
	proxy_send_timeout 10000;
	client_max_body_size 100M;

	# location / {
	# 	proxy_pass http://django;
	# }

	location /api/static/ {
		alias /api/static/;
	}

	# location /label_studio/ {
	# 	rewrite ^/label_studio/(.*)$ /$1 break;
	# 	proxy_pass http://label_studio:8080/;
	# 	proxy_set_header Host $host;
	# 	proxy_set_header X-Real-IP $remote_addr;
	# 	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	# 	proxy_set_header X-Forwarded-Proto $scheme;
	# 	proxy_set_header X-Script-Name /label_studio;
	# 	proxy_redirect ~^http://[^/]+/(.*)$ http://$host/label_studio/$1;
	# 	proxy_redirect ~^/(.*)$ /label_studio/$1;
	# }

	# location /label_studio/static/ {
	# 	alias /label_studio/data/static/;
	# }

	location / {
		proxy_pass http://frontend;
	}

	# location /static/ {
	# 	alias /static/;
	# }

	location /api/ {
		proxy_pass http://django;
	}

	location /admin/ {
		proxy_pass http://django;
	}

	location /static/admin/ {
		proxy_pass http://django;
	}

	location /media/ {
		proxy_pass http://django;
	}
}