upstream django {
        server backend:8000;
}

server {
        listen 80;
        listen [::]:80;

        server_name kinase-pubparser-backend.mbgroup.bio www.kinase-pubparser-backend.mbgroup.bio;
    server_tokens off;

        # location / {
        #       proxy_pass http://django;
        # }

        location / {
        return 301 http://kinase-pubparser-backend.mbgroup.bio$request_uri;
    }

        location /static/ {
                alias /static/;
        }

        location /.well-known/acme-challenge/ {
        root /var/www/certbot;
		    }
}

server {
    listen 443;
    listen [::]:443;

    ssl on;

    server_name kinase-pubparser-backend.mbgroup.bio;

    ssl_certificate /etc/nginx/ssl/live/kinase-pubparser-backend.mbgroup.bio/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/kinase-pubparser-backend.mbgroup.bio/privkey.pem;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;  # <-
        proxy_set_header Host $http_host;
        proxy_redirect off;

        if (!-f $request_filename) {
            proxy_pass http://kinase-pubparser-backend.mbgroup.bio;
            break;
        }
    }
}