# Generated by Django 3.2.20 on 2023-08-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='saved_date_time',
            field=models.DateTimeField(default='2023-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='answer',
            name='source_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='source_paper',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='question',
            name='saved_date_time',
            field=models.DateTimeField(default='2023-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='Llamology',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='model_type',
            field=models.CharField(choices=[('chatGPT', 'chatGPT'), ('AI21', 'AI21'), ('OpenAssistant', 'OpenAssistant'), ('BioGPT', 'BioGPT'), ('BioGPT-ft', 'BioGPT-ft'), ('Llama2', 'Llama2'), ('-', '-')], default='-', max_length=40),
        ),
    ]
