# Generated by Django 3.2.21 on 2023-09-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_auto_20230905_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papers',
            options={'verbose_name': 'paper', 'verbose_name_plural': 'papers'},
        ),
        migrations.AddField(
            model_name='papers',
            name='highlited_attachment',
            field=models.FileField(default='-', upload_to='papers'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='paper_attachment',
            field=models.FileField(default='-', upload_to='papers'),
        ),
    ]
