# Generated by Django 3.2.21 on 2023-09-26 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_auto_20230921_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_answer_count', models.IntegerField(default=0)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('last_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('conversation_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.dataset')),
            ],
        ),
    ]
