# Generated by Django 3.2.21 on 2023-09-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testdb.conversation'),
            preserve_default=False,
        ),
    ]
