# Generated by Django 3.2.23 on 2024-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0007_question_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='-', max_length=200)),
                ('model_size', models.CharField(default='-', max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='ScoreCard',
        ),
    ]
