# Generated by Django 3.2.23 on 2024-01-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0008_auto_20240128_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='temperature',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='model_type',
            field=models.ForeignKey(default='llama2', on_delete=django.db.models.deletion.SET_DEFAULT, to='testdb.model'),
        ),
    ]
