# Generated by Django 3.2.23 on 2024-01-30 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0009_auto_20240128_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='answer',
        ),
        migrations.AddField(
            model_name='source',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.question'),
        ),
    ]
