# Generated by Django 3.2.23 on 2024-01-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0010_auto_20240129_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='confidence_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='model_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='testdb.model'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='model_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='testdb.model'),
        ),
    ]
