# Generated by Django 3.2.24 on 2024-03-07 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0011_auto_20240130_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_no_context_switch', models.BooleanField(default=False)),
                ('azure_login', models.BooleanField(default=False)),
                ('saved_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
