# Generated by Django 3.2.24 on 2024-03-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0012_frontendsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user_email',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user_group',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
