# Generated by Django 3.2.24 on 2024-03-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0013_auto_20240307_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
