# Generated by Django 3.2.24 on 2024-03-29 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0014_conversation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='chunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(default='-')),
                ('embedding', models.TextField(default='-')),
                ('pca_x', models.FloatField(default=0)),
                ('pca_y', models.FloatField(default=0)),
                ('pca_z', models.FloatField(default=0)),
                ('chunk_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('chunk_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.dataset')),
                ('chunk_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.papers')),
            ],
        ),
    ]
