# Generated by Django 3.2.25 on 2024-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0015_chunks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunks',
            options={'verbose_name': 'chunk', 'verbose_name_plural': 'chunks'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='confidence_score',
            new_name='relevance_score',
        ),
        migrations.AddField(
            model_name='answer',
            name='relevance_score',
            field=models.FloatField(default=0),
        ),
    ]
