# Generated by Django 3.2.25 on 2024-04-10 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0016_auto_20240409_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='highlited_attachment',
            new_name='highlighted_attachment',
        ),
    ]
