# Generated by Django 3.2.25 on 2024-04-24 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0017_rename_highlited_attachment_papers_highlighted_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source_paper',
            new_name='source_doc',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_page',
            new_name='source_pointer',
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField(default='-')),
                ('video_link', models.TextField(default='-')),
                ('video_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('video_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.dataset')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
    ]
