# Generated by Django 3.2.25 on 2024-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0018_auto_20240424_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ground_truth',
            field=models.TextField(default='-'),
        ),
    ]
