# Generated by Django 3.2.25 on 2024-04-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0020_dataset_embedding_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunks',
            name='chunk_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.videos'),
        ),
        migrations.AlterField(
            model_name='chunks',
            name='chunk_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.papers'),
        ),
    ]
