# Generated by Django 3.2.25 on 2024-04-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0021_auto_20240429_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='embedding',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='answer',
            name='pca_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='pca_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='pca_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='embedding',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='question',
            name='pca_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='pca_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='pca_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='chunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.chunks'),
        ),
    ]
