# Generated by Django 3.2.25 on 2024-05-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0022_auto_20240429_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontendsettings',
            options={'verbose_name': 'FrontEndSettings', 'verbose_name_plural': 'FrontEndSettings'},
        ),
        migrations.AddField(
            model_name='dataset',
            name='direct_chat_without_docs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frontendsettings',
            name='restriction_without_login',
            field=models.BooleanField(default=False),
        ),
    ]
