# Generated by Django 3.2.25 on 2024-07-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0024_dataset_embedding_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('keyword', 'keyword'), ('yesno', 'yesno'), ('data_query', 'data_query'), ('summarize', 'summarize'), ('complex', 'complex'), ('other', 'other')], default='other', max_length=40),
        ),
    ]
