# Generated by Django 3.2.25 on 2024-07-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0025_auto_20240714_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='chunksize',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='dataset',
            name='overlap',
            field=models.BooleanField(default=False),
        ),
    ]
