# Generated by Django 3.2.25 on 2024-08-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0026_auto_20240725_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_no_context_text',
            field=models.TextField(default='-'),
        ),
    ]
