# Generated by Django 3.2.25 on 2024-08-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0027_answer_answer_no_context_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsettings',
            name='django_login',
            field=models.BooleanField(default=False),
        ),
    ]
