# Generated by Django 3.2.25 on 2024-08-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0028_frontendsettings_django_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsettings',
            name='disable_chat_without_login',
            field=models.BooleanField(default=False),
        ),
    ]
