# Generated by Django 3.2.25 on 2024-08-19 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0029_frontendsettings_disable_chat_without_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisclaimerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='-', max_length=200)),
                ('agreement_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
