# Generated by Django 3.2.25 on 2024-08-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0030_disclaimeragreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='-', max_length=200)),
                ('model_size', models.CharField(default='-', max_length=40)),
                ('model_source', models.CharField(choices=[('ollama', 'ollama'), ('sentence-transformer', 'sentence-transformer')], default='ollama', max_length=40)),
                ('best_distance', models.FloatField(default=0)),
                ('worst_distance', models.FloatField(default=0)),
            ],
        ),
    ]
