# Generated by Django 5.1 on 2024-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0031_embeddingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hallucionation_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='embeddingmodel',
            name='model_source',
            field=models.CharField(choices=[('ollama', 'ollama'), ('sentence-transformer', 'sentence-transformer'), ('huggingface', 'huggingface')], default='ollama', max_length=40),
        ),
    ]