
# Generated by Django 5.1 on 2024-09-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0032_answer_a_hi_answer_ars_lower_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='hallucionation_index',
            new_name='hallucination_index',
        ),
    ]
