# Generated by Django 5.1 on 2024-09-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0033_rename_hallucionation_index_answer_hallucination_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embeddingmodel',
            old_name='best_distance',
            new_name='best_distance_q',
        ),
        migrations.RenameField(
            model_name='embeddingmodel',
            old_name='worst_distance',
            new_name='worst_distance_q',
        ),
    ]