# Generated by Django 5.1.1 on 2024-09-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0035_dataset_a_hi_dataset_b_hi_dataset_c_hi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embeddingmodel',
            old_name='best_distance_a',
            new_name='best_distance_ac',
        ),
        migrations.RenameField(
            model_name='embeddingmodel',
            old_name='worst_distance_a',
            new_name='worst_distance_ac',
        ),
    ]