# Generated by Django 5.1.1 on 2024-09-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0036_rename_best_distance_a_embeddingmodel_best_distance_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingmodel',
            name='best_distance_nac',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='worst_distance_nac',
            field=models.FloatField(default=0),
        ),
    ]