# Generated by Django 5.1.1 on 2024-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0039_remove_dataset_a_hi_remove_dataset_b_hi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='a_HI',
            new_name='a_hi',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='ARS_lower_range',
            new_name='ars_lower_range',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='ARS_upper_range',
            new_name='ars_upper_range',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='b_HI',
            new_name='b_hi',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='c_HI',
            new_name='c_hi',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='QRS_lower_range',
            new_name='qrs_lower_range',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='QRS_upper_range',
            new_name='qrs_upper_range',
        ),
        migrations.AddField(
            model_name='answer',
            name='top_k',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='answer',
            name='top_p',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='answer',
            name='temperature',
            field=models.FloatField(default=0.4),
        ),
    ]