# Generated by Django 5.2.4 on 2025-07-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0042_alter_dataset_chunking_method_papersections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='distance',
            new_name='vector_distance_raw',
        ),
        migrations.AddField(
            model_name='source',
            name='bm25_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='bm25_score_raw',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='secondary_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='vector_score',
            field=models.FloatField(default=0),
        ),
    ]
