# Generated by Django 5.2.8 on 2025-12-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0044_dataset_use_bm25'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='rerank_score',
            field=models.FloatField(default=0),
        ),
    ]
