# Generated by Django 5.2.9 on 2026-01-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0046_dataset_use_reranker'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='bm25_score_answer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='bm25_score_raw_answer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='rerank_entailment',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='source',
            name='vector_distance_answer_raw',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='vector_score_answer',
            field=models.FloatField(default=0),
        ),
    ]
