# Generated by Django 5.2.11 on 2026-04-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0049_dataset_documents_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='hallucination_index',
            new_name='hallucination_index_by_equation',
        ),
        migrations.AddField(
            model_name='answer',
            name='hallucination_index_by_ml',
            field=models.FloatField(default=0),
        ),
    ]
