# Generated by Django 5.2.11 on 2026-04-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0050_rename_hallucination_index_answer_hallucination_index_by_equation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='keyword_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='rerank_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='semantic_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='keyword_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rerank_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='semantic_score',
            field=models.FloatField(default=0),
        ),
    ]
