# Generated by Django 5.2.11 on 2026-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0051_answer_keyword_score_answer_rerank_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='translated_answer_text',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='question',
            name='translated_question_text',
            field=models.TextField(default='-'),
        ),
    ]
