# Generated by Django 5.2.15 on 2026-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0055_alter_dataset_documents_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(choices=[(1, 'correct'), (0, 'n/a'), (-1, 'incorrect')], default=0),
        ),
    ]
