name: frontend CI

on:
  push:
    paths:
      - "frontend/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "frontend/**"
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        always-auth: true
        registry-url: https://npm.pkg.github.com/
        scope: '@mb-group'

    - name: Install
      run: npm install
      working-directory: ./frontend

    - name: Build
      run: npm run build --if-present
      working-directory: ./frontend
      env:
        GENERATE_SOURCEMAP: false

    - name: Test
      run: npm run test:ci --if-present
      working-directory: ./frontend